## Numpy Splitting array

-- Splitting is reverse operation of joining

--Joining merges multiple arrays into one and splitting breaks one array into multiple.

--we use array_split() for splitting arrays,we pass it array we want to split and number of splits.




In [2]:
#Example- split the array into 3 parts
import numpy as np
array=np.array([1,2,3,4,5,6])
new_array=np.array_split(array,3)
new_array

[array([1, 2]), array([3, 4]), array([5, 6])]

In [3]:
#Example- split the array into 3 parts
import numpy as np
array=np.array([1,2,3,4,5,6])
new_array=np.split(array,3)
new_array

[array([1, 2]), array([3, 4]), array([5, 6])]

In [6]:
#split the particular array in 4 parts
import numpy as np
array=np.array([1,2,3,4,5,6])
new_array=np.array_split(array,4)
new_array   #if the array has less elements than required it will adjust for end accordingly

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [8]:
## Example-Split into arrays
# if you split an array into 3-arrays you can access them from the result just like an array element
import numpy as np
array=np.array([1,2,3,4,5,6])
new_array=np.array_split(array,3)
print(new_array[0])
print(new_array[1])
print(new_array[2])

[1 2]
[3 4]
[5 6]


In [14]:
#example- use same syntax when spliting 2d arrays 
#use the array_split() method,pass on the array you want to split and number of split you want to do
#split the 2d arrays into three 2-d array

import numpy as np
array=np.array([[1,2,13],[3,4,14],[5,6,15],[7,8,16],[9,10,17],[11,12,18]])
new_array=np.array_split(array,3)
new_array


[array([[ 1,  2, 13],
        [ 3,  4, 14]]),
 array([[ 5,  6, 15],
        [ 7,  8, 16]]),
 array([[ 9, 10, 17],
        [11, 12, 18]])]

In [15]:
#Example-Split the 2-d array into three 2-d array along rows
import numpy as np
array=np.array([[1,2,13],[3,4,14],[5,6,15],[7,8,16],[9,10,17],[11,12,18]])
new_array=np.array_split(array,3,axis=1)
new_array


[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]),
 array([[13],
        [14],
        [15],
        [16],
        [17],
        [18]])]

## Numpy array Search 

-- you can an array for a certain value and return the indexes that get a match 

-- To search array you can used where() method

In [16]:
#Example- find the index where the value is four
import numpy as np
array=np.array([1,2,3,4,5,4,4])
x=np.where(array==4)
x

(array([3, 5, 6], dtype=int64),)

In [18]:
#find the indexes where the values are even
import numpy as np
array=np.array([1,2,3,4,5,4,4,5,6,7,8])
x=np.where(array%2==0)
x

(array([ 1,  3,  5,  6,  8, 10], dtype=int64),)

In [20]:
#find the indexes where the values are odd
import numpy as np
array=np.array([1,2,3,4,5,4,4,5,6,7,8])
x=np.where(array%2!=0)
x

(array([0, 2, 4, 7, 9], dtype=int64),)

## Search Sorted

-- this method perform binary search in the array and return the index where the specified value would be inserted to maintain search order.


In [21]:
# Example-
array=np.array([6,7,8,9])
x=np.searchsorted(array,7)
x

1

In [22]:
# Example-
array=np.array([6,7,8,9])
x=np.searchsorted(array,7,side='right')
x

2

## np array sort

-- sorting means putting in ordered sequence

--np, ndarray object has function called sort() 

In [23]:
#example- 
array=np.array([3,2,0,1])
print(np.sort(array))

[0 1 2 3]


In [29]:
#example- sort the array alphabetically
array=np.array(['banana','cherry','apple'])
np.sort(array)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [30]:
#example- sort the boolean array 
array=np.array([True,False,True])
printnp.sort(array)

array([False,  True,  True])

## sort 2-d array
- if you use sort method on a 2-d array both array will be sorted


In [31]:
#example-
array=np.array([[3,2,4],[5,0,1]])
print(np.sort(array))

[[2 3 4]
 [0 1 5]]


## np array Filter
-- getting some element out of existing array and creating new array out of them is called filtering

--in np you filter an array using a boolean index list

--if the value at an index is true that element is contained in filtered array,if the value of that index is false that element excluded from the filtered array

In [35]:
#example-create an array from the element 0 and 2 
array=np.array([41,42,43,44])
x=[False,True,False,True]
new_array=array[x]
print(new_array)

[42 44]


In [36]:
#creating filter array that will return values higher than 42
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)



[False, False, True, True]
[43 44]


In [37]:
#create a filter array that will return only even value

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]
