# Numpy array indexing

__1. Accessing 2-D arrays: To access elements from 2-D array we can use commas seperate integers representing the 
                           dimensions and index of the element.
                         

In [2]:
import numpy as np

arr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Second element on first row:",arr[0,1])

Second element on first row: 2


In [4]:
import numpy as np

arr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Fifth element on second row:",arr[1,4])

Fifth element on second row: 10


# Negative Indexing:

Use negative indexing to access an array from the end.

In [5]:
import numpy as np

arr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Last element from second dimension:",arr[1,-1])

Last element from second dimension: 10


# Numpy array copy vs view:

        > The main difference between a copy and a view of an array is that, the copy is the new array, and view is just the view of the original array.
        > The copy owns the data and any changes made to the copy will not affect the original array, and the any changes made to the original array will not effect the copy.
        > The view does'nt own the data and any changes made to the view will affect the original array, and any changes made the original array will effect the view.

In [9]:
# copy()
# make a copy change the original array and display both the arrays

import numpy as np
array=np.array([1,2,3,4,5])
x=array.copy()
array[0]=42
print(array)
print(x)


# NOTE: The copy SHOULD NOT be affected  by the changes made to the original array.

[42  2  3  4  5]
[1 2 3 4 5]


In [10]:
# view()
# make a view change the original array and display both the arrays

import numpy as np
array=np.array([1,2,3,4,5])
x=array.view()
array[0]=42
print(array)
print(x)


# NOTE: The view SHOULD be affected by the changes made to the original array.

[42  2  3  4  5]
[42  2  3  4  5]


# Numpy Array Shape:
    
        > The shape of an array is the number of elements in each dimensions.
        > Numpy array have an attribute called "SHAPE".

In [11]:
import numpy as np

array=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(array.shape)


# The example above (2,4) which means that, the array has 2-dimensions where the first has 2 elements and second has 4 
# elements

(2, 4)


# Numpy array reshaping:

            > Reshaping means changing the shape of an array.
            > The shape of an array is the number of dimensions in each elements.
            > By reshaping we can add or remove dimensions or change number of elements in each dimensions.

In [12]:
# Reshaping from 1-D to 2-D
# Converting the following 1-D array with 12 elements into a 2-D array.

import numpy as np

array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array=array.reshape(4,3)
print(new_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
# Reshaping from 1-D to 3-D

import numpy as np

array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array=array.reshape(2,3,2)
print(new_array)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Numpy array iterating:

        > Iterating means going to elements one-by-one.
        > As, we deal with multi-dimensional arrays in numpy we can use it by for loop in python.
        > If we iterate on a 1-D array it will go through each element one by one.

In [14]:
array=np.array([1,2,3,4,5])
for x in array:
    print(x)

1
2
3
4
5


# Iterating 2-D arrays:

In [16]:
array=np.array([[1,2,3],[4,5,6]])
for x in array:
    print(x)

[1 2 3]
[4 5 6]


# Numpy Joining array:

        > Joining means putting contents of 2 or more arrays in single array.
        > We pass a sequence of arrays that we want to join to concatenate function along with the axis.
        > If the axis is not explicitly pass it will be taken zero.

In [18]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])

new_array=np.concatenate((array1,array2))
new_array

array([1, 2, 3, 4, 5, 6])

In [21]:
array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])

new_array=np.concatenate((array1,array2),axis=1)
new_array

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [22]:
array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])

new_array=np.concatenate((array1,array2),axis=0)
new_array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Joining arrays using stack function:

        > Stack is same as concatenation, the only difference is that stacking is done along the new axis.
        > We pass a sequence of array that we want to join the stack method.

In [23]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])

new_array=np.stack((array1,array2),axis=1)
new_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])

new_array=np.stack((array1,array2),axis=0)
new_array

array([[1, 2, 3],
       [4, 5, 6]])