In [5]:
import numpy as np

In [20]:
l=[12,23,34,54,67,78]
l

[12, 23, 34, 54, 67, 78]

In [21]:
type(l)

list

In [22]:
a1=np.array(l)

In [23]:
type(a1)

numpy.ndarray

In [24]:
a1.data#memmory address

In [25]:
a1.dtype

dtype('int32')

In [26]:
a1=a1.astype(float)#int to float

In [28]:
a1

array([12., 23., 34., 54., 67., 78.])

In [29]:
a1.dtype

dtype('float64')

In [30]:
np.arange(0,20)#equal space between 0 to 20

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.arange(0,21,2)# 0to21 with space 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
np.arange(0,50,5)#generate no betn 0 to 50 with a space of 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [36]:
a2=np.arange(0,23)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [37]:
a2.shape #shape of array

(23,)

In [38]:
a2.size #size

23

In [39]:
a2.ndim #dimension

1

In [40]:
a2.itemsize #bytes consumed by one element of an array object

4

In [41]:
a2.nbytes # bytes consumed by an array object

92

In [42]:
a2.nbytes

92

In [43]:
len(a2) #length of array

23

In [44]:
np.zeros(12) # generate array of zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.ones(10) # generate array of ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.repeat(5,4) #repeat 5 four times in array

array([5, 5, 5, 5])

In [48]:
a3=np.array([12,23,34]) #repeat each element in array five time
np.repeat(a3,5)


array([12, 12, 12, 12, 12, 23, 23, 23, 23, 23, 34, 34, 34, 34, 34])

In [49]:
np.full(5,8)

array([8, 8, 8, 8, 8])

In [51]:
"""1.generate array of even no
   2. generate array of odd no"""
a4=np.arange(1,100)
a4[a4%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [52]:
a4=np.arange(1,100)
a4[a4%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [54]:
np.linspace(10,25,6)#generate evenly spaced 4 numbers betn 10to20


array([10., 13., 16., 19., 22., 25.])

In [55]:
np.random.random(4) #create random valuve

array([0.07416038, 0.15448592, 0.22889228, 0.41270735])

In [56]:
np.random.randint(0,100,10) #create random integer no

array([20, 15, 47, 52, 93, 34, 52, 60, 49, 34])

In [57]:
a5=np.random.uniform(5,10,8)
a5

array([9.09187134, 6.98392092, 8.63352697, 9.43277785, 7.50815614,
       8.33104354, 5.87828403, 7.01453488])

In [58]:
np.floor(a5)

array([9., 6., 8., 9., 7., 8., 5., 7.])

In [59]:
np.trunc(a5)

array([9., 6., 8., 9., 7., 8., 5., 7.])

In [61]:
#to check the version of numpy
print(np.__version__)


1.20.3


In [ ]:
Data types in Numpy
i
b
u
f
c
m
o
s
u

In [3]:
import numpy as np

In [ ]:
ast=np.array(['dipali','karan','joy'])
print(ast.dtype)

In [1]:
a1

NameError: name 'a1' is not defined

In [ ]:
Operation on array

In [5]:
ar=np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
ar.sum()

45

In [7]:
cs=np.cumsum(ar)
print(cs)

[ 0  1  3  6 10 15 21 28 36 45]


In [8]:
print(np.cumsum(ar))

[ 0  1  3  6 10 15 21 28 36 45]


In [9]:
ar.min()

0

In [10]:
ar.max()

9

In [11]:
ar.mean()

4.5

In [12]:
np.median(ar)

4.5

In [14]:
ar=np.array([78,89,54,12,79,65])
ar

array([78, 89, 54, 12, 79, 65])

In [15]:
ar.argmin()

3

In [16]:
ar.argmax()

1

In [17]:
np.var(ar)

640.4722222222222

In [18]:
np.std(ar)

25.307552671529148

In [19]:
ar

array([78, 89, 54, 12, 79, 65])

In [21]:
np.percentile(ar,75)

78.75

In [22]:
np.percentile(ar,50)

71.5

In [23]:
np.percentile(ar,25)

56.75

In [24]:
np.percentile(ar,0)

12.0

In [25]:
np.percentile(ar,100)

89.0

In [26]:
np.percentile(ar,60)

78.0

copy of an array
copy should not be affected by the changes made to the original array

In [30]:
ac=np.array([12,23,34,45,56])
y=ac.copy()
ac[3]=89
print(ac)
print(y)

[12 23 34 89 56]
[12 23 34 45 56]


View
in view should be affected by the changes made to the original array

In [31]:
ac=np.array([12,23,34,45,56])
y=ac.view()
ac[3]=89
print(ac)
print(y)

[12 23 34 89 56]
[12 23 34 89 56]


Difference betn copy and view
copy is a new array and view is just a view of the original array


In [32]:
import numpy as np
ac=np.array([12,23,34,45,56])
y=ac.copy()
x=ac.view()

print(y.base)
print(x.base)

None
[12 23 34 45 56]


reshaping

In [35]:
ar=np.array([1,2,34,45,56,67,78,89])
ar

array([ 1,  2, 34, 45, 56, 67, 78, 89])

In [36]:
n=ar.reshape(2,4)
print(n)

[[ 1  2 34 45]
 [56 67 78 89]]


iterating array

In [37]:
for i in ar:
    print(i)

1
2
34
45
56
67
78
89


In [39]:
for i in n:
    print(i)
    

[ 1  2 34 45]
[56 67 78 89]


In [40]:
for i in n:
    for j in i:
        print(j)

1
2
34
45
56
67
78
89


In [ ]:
joining array using stack function

In [41]:
c=np.array([1,2,3])
d=np.array([7,8,12])
c

array([1, 2, 3])

In [42]:
d

array([ 7,  8, 12])

In [44]:
con1=np.stack((c,d),axis=1)
print(con1)

[[ 1  7]
 [ 2  8]
 [ 3 12]]


In [45]:
con1=np.stack((c,d),axis=0)
print(con1)

[[ 1  2  3]
 [ 7  8 12]]


In [ ]:
hstack
along rows

In [46]:
c=np.array([1,2,3])
d=np.array([7,8,12])
con1=np.hstack((c,d))
print(con1)

[ 1  2  3  7  8 12]


In [ ]:
vstack
along columns

In [47]:
c=np.array([1,2,3])
d=np.array([7,8,12])
con1=np.vstack((c,d))
print(con1)

[[ 1  2  3]
 [ 7  8 12]]


In [ ]:
dstack()
along height wich is same as depth

In [49]:
c=np.array([1,2,3,89])
d=np.array([7,8,12,75])
con1=np.dstack((c,d))
print(con1)

[[[ 1  7]
  [ 2  8]
  [ 3 12]
  [89 75]]]


In [ ]:
splitting array
breaks array into multiple

In [51]:
a1=np.array([31,21,30,44,15,61,70,18,9])
a1

array([31, 21, 30, 44, 15, 61, 70, 18,  9])

In [54]:
n=np.array_split(a1,4)
print(n)

[array([31, 21, 30]), array([44, 15]), array([61, 70]), array([18,  9])]


In [55]:
a1=np.array([1,2,3,4,5,6,7,8,9])
n=np.array_split(a1,5)
print(n)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]


2D array splitting

In [56]:
a2=np.array([[1,2,3],[7,8,9],[10,11,12]])
print(a2)

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [57]:
n1=np.array_split(a2,2)
print(n1[1])

[[10 11 12]]


In [58]:
print(n1[0])

[[1 2 3]
 [7 8 9]]


hsplit

In [59]:
a2=np.array([[1,2,3],[7,8,9],[10,11,12]])
print(a2)

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [60]:
n1=np.hsplit(a2,3)
print(n1)

[array([[ 1],
       [ 7],
       [10]]), array([[ 2],
       [ 8],
       [11]]), array([[ 3],
       [ 9],
       [12]])]


vsplit

In [63]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [64]:
n1=np.vsplit(a2,2)
print(n1)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


dsplit

In [66]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [69]:
con1=np.dsplit(c,3)
print(con1)

[array([[[1],
        [4],
        [7]]]), array([[[2],
        [5],
        [8]]]), array([[[3],
        [6],
        [9]]])]


In [ ]:
# sum of all numbers in a 2D array
# minimum and maximum value
# 50 percentile
# access all the elements of array except first one
# addition of matrix


In [ ]:
Searching array

In [67]:
arr=np.array([78,45,23,12,89,65,80,44,32,44,45])
a=np.where(arr==44)
print(a)

(array([7, 9], dtype=int64),)


In [68]:
arr=np.array([78,45,23,12,89,65,80,44,32,44,45])
a=np.where(arr==12)
print(a)

(array([3], dtype=int64),)


Replace element in an array

In [70]:
ar=np.arange(1,21)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
rep=np.where(ar%2==0,0,ar)
print(rep)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0]


missing values in array

In [74]:
a=np.array([1,np.nan,78,86,90,np.nan,8,np.nan])
a

array([ 1., nan, 78., 86., 90., nan,  8., nan])

In [75]:
np.isnan(a)

array([False,  True, False, False, False,  True, False,  True])

In [76]:
a

array([ 1., nan, 78., 86., 90., nan,  8., nan])

In [77]:
a[np.isnan(a)]=65 # replace all missing value

In [78]:
a

array([ 1., 65., 78., 86., 90., 65.,  8., 65.])

In [79]:
np.isnan(a).any() # check array has any null value

False

common items bet two arrays

In [81]:
a=np.array([10,11,12,13,14,15,16,17])
b=np.array([12,13,45,67,34,10,11,78])

In [83]:
np.intersect1d(a,b)

array([10, 11, 12, 13])

Remove common element

In [84]:
a

array([10, 11, 12, 13, 14, 15, 16, 17])

In [85]:
b

array([12, 13, 45, 67, 34, 10, 11, 78])

In [86]:
np.setdiff1d(a,b)

array([14, 15, 16, 17])

In [87]:
np.setdiff1d(b,a)

array([34, 45, 67, 78])

check for elements in an array using isin()

In [91]:
a=np.array([100,20,130,40,150,60,78])
a

array([100,  20, 130,  40, 150,  60,  78])

In [93]:
np.isin(a,[40,60])

array([False, False, False,  True, False,  True, False])

In [ ]:
reverse array

In [ ]:
a=np.array([100,20,130,40,150,60,78])
a

In [89]:
np.flip(a)

array([ 78,  60, 150,  40, 130,  20, 100])

In [ ]:
sort array


In [94]:
b=np.array([67,43,23,11,89,65,45,88])
b

array([67, 43, 23, 11, 89, 65, 45, 88])

In [95]:
np.sort(b)

array([11, 23, 43, 45, 65, 67, 88, 89])

In [ ]:
operation 2D array

In [99]:
a=np.array([[100,2,93],[41,5,6],[7,8,90]])
a

array([[100,   2,  93],
       [ 41,   5,   6],
       [  7,   8,  90]])

In [100]:
np.amin(a,axis=1)

array([2, 5, 7])

In [101]:
np.amin(a,axis=0)

array([7, 2, 6])

In [102]:
np.amax(a,axis=1)

array([100,  41,  90])

In [104]:
np.amax(a,axis=0)

array([100,   8,  93])